name: Build and deploy website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: npm run build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
