name: Build and deploy website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: npm run build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}  
          publish_dir: build
